### ISSUE TITLE
New NixOS wiki

### ISSUE THREAD

**Issue by Mic92** [fcrespo82/dotfiles#1]
I just saw your edit on the "Installing from Linux" article in nixos.wiki and just want to let you know that we have https://wiki.nixos.org: https://github.com/NixOS/foundation/issues/113

**Comment by fcrespo82** [comment]
Thanks for the heads up!I found it eventually.Em 1 de ago. de 2024, à(s) 09:17, Jörg Thalheim ***@***.***> escreveu:﻿
I just saw your edit on the "Installing from Linux" article in nixos.wiki and just want to let you know that we have https://wiki.nixos.org: NixOS/foundation#113
